#logging
logging:
  level:
    mnu.bbs.domain.mapper: debug
spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://120.78.190.112:3306/forum?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: 25htLMm!b
  driver-class-name: com.mysql.jdbc.Driver
  maxActive: 20 #最大连接数量
  initialSize: 1 #初始Connection数量
  maxWait: 60000
  minIdle: 1 #最小连接数量
 http:
   multipart:
     location: C:/forum #虚拟路径
 resources:
   static-locations: classpath:/static/,file:${spring.http.multipart.location} #加入到静态资源路径中
file-upload-path: c:/forum
