spring:
  mail:
    host: smtp.163.com
    username: mrzangxiaoxian@163.com
    password: yeshi3...
  freemarker:
    suffix: .html
    request-context-attribute: request
    charset: UTF-8
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev
#MyBatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xiaobingby.sys.entity;com.xiaobingby.oss.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #自定义填充策略接口实现
    meta-object-handler: mnu.bbs.config.mybatis.MyMetaObjectHandler
  configuration:
    cache-enabled: false